name: setup-python
description: Setup Python 3.10

inputs:
  cache-ver:
    description: Cache version
    required: true
  working-directory:
    description: Working directory
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=python" >> $GITHUB_ENV
      shell: bash