name: CI

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        requred: false
        default: 'false'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Filter by paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend:
              - '.github/workflows/**'
              - 'python/**'
    outputs:
      backend: ${{ steps.filter.outputs.backend }}

  backend-lint:
    needs:
      - detect-changes
    if: ${{ !cancelled() && needs.detect-changes.outputs.backend == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python
        with:
          cache-ver: ${{ vars.CACHE_VER }}
      - name: Generate list of directories containing modified Python files
        run: |
          CHANGE_DIRS=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep '\.py$' | xargs -I{} dirname {} | sort | uniq)
          echo "CHANGE_DIRS=$(echo $CHANGE_DIRS | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Lint with flake8
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics ${{ env.CHANGE_DIRS }}
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics ${{ env.CHANGE_DIRS }}